CREATE TABLE color (
  idcolor      NUMBER        GENERATED ALWAYS AS IDENTITY,
  NAME   VARCHAR2(100) NOT NULL,
  DESCRIPTION  VARCHAR(500) NULL,
  STATUS   NUMBER(1,0) NOT NULL,
  CHECK (STATUS BETWEEN 0 and 1)
);
 INSERT INTO COLOR (NAME,DESCRIPTION,STATUS)
 VALUES('RED','RED COLOR',1)
 
 SELECT * FROM COLOR